### ISSUE TITLE
About  preprocessing of datasets 

### ISSUE THREAD

**Issue by Yuanqin-He** [Yanfeng-Zhou/XNet#15]
作者大大，您好！卑微的一枚本科生求助！！
https://github.com/Yanfeng-Zhou/XNet/issues/8#issuecomment-1826325353
我想问问这句话是什么意思，应该如何处理数据集。
如果可以的话，可以给一下联系方式吗，我想知道数据是如何处理的，我看着这篇回答，自己摸索着处理，不知道过程是否正确，但前面陆续暴露出的问题，和该篇提问篇作者一样。

**Comment by Yanfeng-Zhou** [comment]
If you have questions you can also send me an email (the email address is in our paper)

**Comment by Yuanqin-He** [comment]
Thank you！！！
Excuse me!
I don't know if my my dataset has been processed correctly.&nbsp;
If possible?&nbsp;Could you please send me the processed GlaS dataset？
Also, if possible, you can also send me a copy of the trained model. If not, I'm very sorry.
Finally, thank you very much for your help.
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Feb 20, 2024 06:52 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [Yanfeng-Zhou/XNet] About  preprocessing of datasets  (Issue #15)

&nbsp;



 
If you have questions you can also send me an email (the email address is in our paper)
