### ISSUE TITLE
小波变换会造成图片尺寸变小

### ISSUE THREAD

**Issue by DreamerrW** [Yanfeng-Zhou/XNet#2]
使用了小波变换后，我发现我的图片变成了原来的一半，请问作者是怎么解决这个问题的？分割掩码也要下采样吗？

**Comment by Yanfeng-Zhou** [comment]
注意我的代码中的/config/augmentation/online_aug.py中，在训练你可以将输入图像resize到任意大小！小波变换的目的是为了得到L和H图像，它们的大小在训练中可以随意调整，当然也可以resize到raw image的尺寸。我的程序中，mask的尺寸会自动与输入图像尺寸保持一致！

Question: Wavelet transform will reduce the image size by half, how to deal with it？

Answer: Note that in /config/augmentation/online_aug.py in my code, you can resize the input image to any size during training! The purpose of wavelet transform is to obtain L and H images. Their size can be adjusted at will during training, and of course they can also be resized to the size of the raw image. In my code, the size of the mask will automatically be consistent with the size of the input image!

**Comment by DreamerrW** [comment]
好的，感谢！

**Comment by MinyeShao** [comment]
同问作者大大，数据处理readme中没写的很详细我想确认下我想的是否正确
1.对于CREMI数据，是不是原始尺寸1250*1250，滑动窗口切成 256*256，然后online_aug.py改成128*128，然后小波变换分成LH两个64*128size大小的输入吗
2.CREMI数据的掩码处理用的也是res_image_mask.py吗

**Comment by Yanfeng-Zhou** [comment]
正确顺序应该是这样的：（1）滑窗裁剪至256*256（同时掩码也需要一摸一样的操作），（2）小波变换得到128*128的L和H（掩码也可以resize一份128*128的，但不强求，因为后面训练的时候online_aug.py会将mask和image的size调整到一致），（3）训练模型（训练尺寸根据online_aug.py里的参数来确定，我在论文中用的是128*128）
res_image_mask.py是给conresnet生成掩码用的，至于conresnet为什么需要这种掩码请看它的原论文

**Comment by MinyeShao** [comment]
> 正确顺序应该是这样的：（1）滑窗裁剪至256_256（同时掩码也需要一摸一样的操作），（2）小波变换得到128_128的L和H（掩码也可以resize一份128_128的，但不强求，因为后面训练的时候online_aug.py会将mask和image的size调整到一致），（3）训练模型（训练尺寸根据online_aug.py里的参数来确定，我在论文中用的是128_128） res_image_mask.py是给conresnet生成掩码用的，至于conresnet为什么需要这种掩码请看它的原论文

好快！谢谢回复，对于Xnet2D，请问CREMI数据生成掩码的过程在代码有给出吗
