### ISSUE TITLE
About wavelet3D.py

### ISSUE THREAD

**Issue by Seconight** [Yanfeng-Zhou/XNet#6]
Hi! Thank you for your great work! 🤗
And I have a few questions:

- What is the process when processing two 3D dataset LA & LiTS? My understanding is that run `preprocessing.py` first and then run the `wavelet3D.py`, the folders `L` and `H` are the inputs of the model. Is that right?
- And when I run `wavelet3D.py` with LiTS, python throw TypeError:
 
<img width="827" alt="image" src="https://github.com/Yanfeng-Zhou/XNet/assets/54622036/be8a59fc-1dd7-4b34-bbff-0f46bbc8a72b">
it looks like the type of `LLL` int line 49 is not `Image`, and I add `LLL = sitk.GetImageFromArray(LLL)` before line 49, is that OK?

Thank you for your reply!

**Comment by Yanfeng-Zhou** [comment]
1. You are right. First, you need to download the dataset, then preprocess (**preprocess.py**), and finally generate L and H (**wavelet3D.py**) based on the preprocessing results.
2. As in **line 69**, **LLL = sitk.GetImageFromArray(LLL)** should be added before **line 49**. This was an oversight on my part, thank you for your correction.

**Comment by Seconight** [comment]
I got it. Thank you very much!

**Comment by Seconight** [comment]
Hello, I have one more question.
I tried to run the model on the LA dataset(3D), however, the result was not good...
<img width="219" alt="image" src="https://github.com/Yanfeng-Zhou/XNet/assets/54622036/e67eddf1-b3d1-42c0-ab5b-7dda97712e56">
For data processing, I run the `preprocessing.py` and then use `wavelet3D.py` to get L and H of the images. For data postprocessing, I run the `test_3dxnet.py` and then `postprocess.py` and then `tools/eval.py`. Is there anything wrong? Or is there anything I was not paying attention to? 
Thank you for your reply and patience!

**Comment by Yanfeng-Zhou** [comment]
This may be caused by inconsistent settings of some hyperparameters between training and testing. As stated in our paper, **patch size=(96,96,80)** for training and inference, **patch_overlap=(48, 48, 40)** for testing,  **threshold** is determined by the best results obtained from training.

In addition, please note that the current **best_Jc_model** is saved with a bug. Please do not use the finally generated **best_Jc_model** for inference. Instead, use the model generated in the training process for inference.

**Comment by Seconight** [comment]
It works!!!🥰Thank you again! By the way, where can I get the threshold? It didn't appear in the file.

**Comment by Yanfeng-Zhou** [comment]
Threshold will only appear in two-category segmentation, and it will be printed out during the training process. If you forget to record the corresponding threshold, you can use threshold=0.5 for inference.

**Comment by Seconight** [comment]
OK. I got it. Wishing you success in your research.
